apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    {{- include "cloudnative.labels" . | nindent 4 }}
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP