apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cloudnative.fullname" . }}-postgres
  labels:
    {{- include "cloudnative.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.postgres.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}